kind: pipeline
type: docker

build:
  image: armhfbuild/buildpack-deps:jessie-scm
  commands:
    - git clone https://github.com/jwilder/nginx-proxy upstream
    - sed -i 's/FROM nginx:1\.9\../FROM armhfbuild\/nginx:1.9.9/' upstream/Dockerfile
    - sed -i 's/https:\/\/.*\/forego/https:\/\/github.com\/djmaze\/armhf-forego\/releases\/download\/v0.16.1\/forego/' upstream/Dockerfile
    - sed -i 's/amd64/armhf/' upstream/Dockerfile

publish:
  docker:
    image: armhfplugins/drone-docker:docker-caching
    context: upstream
    file: upstream/Dockerfile
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: valekoz/nginx-proxy

cache:
  mount:
    - /drone/docker
